name: EAS Android Preview Build on Push

on:
  push:
    branches:
      - main
      - master

jobs:
  build:
    name: Build Android APK
    runs-on: ubuntu-latest
    steps:
      - name: 🏗 Checkout repository
        uses: actions/checkout@v4

      - name: 🟢 Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn

      - name: 📦 Setup Expo and EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: 📥 Install dependencies
        run: yarn install --frozen-lockfile

      - name: 🚀 Trigger EAS Cloud Build
        run: eas build --platform android --profile preview --non-interactive
